### PR TITLE
Update TR Locales

### PR DESCRIPTION
**Pull request by mikropsoft**

### CODE REVIEW

**Comment by h4h13** [comment]
Hey, can you brief what you have done please

**Comment by mikropsoft** [comment]
> Hey, can you brief what you have done please



> Hey, can you brief what you have done please

When I first opened the pull request and the code was incorporated into the project, the code had changed like this (from about 1100 lines to around 200 lines). Upon checking, I noticed that some translations were missing, so I completed the missing ones.

**Comment by h4h13** [comment]
Can you fix the conflicts, I can't merge with confilicts

**Comment by mikropsoft** [comment]
> Can you fix the conflicts, I can't merge with confilicts

Fixed

**Comment by mikropsoft** [comment]
@h4h13

**Comment by mikropsoft** [comment]
Awaiting for merge @h4h13

**Comment by mikropsoft** [comment]
I would also like to point out that since the application does not detect the system language, we always see English in the installation.

**Pull request merged**
