### PR TITLE
Remove transfers showing on summary page

### PR DESCRIPTION
**Pull request by x4nk1t**
This commit hides the transfers from showing up as income / expense.

### CODE REVIEW

**Comment by h-savarala** [comment]
If the selected account is excluded means it will add boolean to transaction
Can't we just use account id to remove them

**Comment by x4nk1t** [comment]
The problem I'm facing is when I transfer balance from A -> B, it will show up as income / expenses in the summary page.
So, as you've said if we exclude the accounts it will no longer show the transaction at all.

**Comment by h4h13** [comment]
But by using an account we're already excluding right wasn't it working

**Comment by x4nk1t** [comment]
it was working but it would exclude all the transaction which I don't want
it to

**Comment by h-savarala** [comment]
Going forward we're treating the transfer as different item so it wont be included in sum

**Comment by x4nk1t** [comment]
yes that's right

**Pull request closed without merging**
